openapi: 3.0.0
info:
  title: Simple Weather API
  version: 1.0.0
  description: A simple API to get weather information based on zip code.
servers:
  - url: https://weather-api-contract-test-b21546a33c5f.herokuapp.com/api/v1
paths:
  /api/v1/weather/{zip_code}:
    get:
      summary: Get Weather Information
      description: Returns weather information for the specified zip code.
      parameters:
        - $ref: '#/components/parameters/ZipCodeParameter'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                zip_code: "12345"
                high_temp: 85
                low_temp: 55
        '400':
          description: Bad Request
          content:
            application/json:
              example:
                error: "Invalid zip code format"
components:
  parameters:
    ZipCodeParameter:
      name: zip_code
      in: path
      required: true
      description: The zip code for which to retrieve weather information.
      schema:
        type: string
        minLength: 5
        maxLength: 5
